/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TugasPraktikum.Bab1.Bab3;

/**
 *
 * @author LA
 */
public class GUI_PengembalianBarang extends javax.swing.JFrame {

    /**
     * Creates new form GUI_PengembalianBarang
     */
    public GUI_PengembalianBarang() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_idkembali = new javax.swing.JTextField();
        txt_namabarangkembali = new javax.swing.JTextField();
        txt_tglkembali = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_jmlkembali = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        memo_dataKembali = new javax.swing.JTextArea();
        btn_cetakKembali = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txt_jmlpinjam = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Data Pengembalian Barang");

        jLabel2.setText("Nama Barang");

        jLabel3.setText("ID Peminjaman");

        jLabel4.setText("Tanggal Pengembalian");

        jLabel5.setText("Jumlah yang Dikembalikan");

        memo_dataKembali.setColumns(20);
        memo_dataKembali.setRows(5);
        jScrollPane1.setViewportView(memo_dataKembali);

        btn_cetakKembali.setText("Cetak Data Pengembalian");
        btn_cetakKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cetakKembaliActionPerformed(evt);
            }
        });

        jLabel6.setText("Jumlah yang Dipinjam");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btn_cetakKembali, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                    .addComponent(txt_namabarangkembali)
                                    .addComponent(txt_idkembali)
                                    .addComponent(txt_tglkembali)
                                    .addComponent(txt_jmlkembali)
                                    .addComponent(txt_jmlpinjam))))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_idkembali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addComponent(txt_namabarangkembali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_tglkembali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_jmlpinjam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_jmlkembali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(26, 26, 26)
                .addComponent(btn_cetakKembali)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cetakKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cetakKembaliActionPerformed
        // TODO add your handling code here:
        memo_dataKembali.setText("");
        dataPeminjamanBarang pinjam = new dataPeminjamanBarang();
        dataPengembalianBarang kembali = new dataPengembalianBarang();
        
        pinjam.SetidPinjam(txt_idkembali.getText());
        pinjam.namaBarangPinjam(txt_namabarangkembali.getText());
        kembali.tglKembali(txt_tglkembali.getText());
        kembali.jmlKembali(Integer.parseInt(txt_jmlkembali.getText()));
        kembali.jmlPinjam(Integer.parseInt(txt_jmlpinjam.getText()));
        
        memo_dataKembali.append("Data Pengembalian Barang Kantor\n");
        memo_dataKembali.append("-----------------------------------------------------\n");
        memo_dataKembali.append("ID Peminjaman : " + pinjam.getidPinjam() + "\n");
        memo_dataKembali.append("Nama Barang : " + pinjam.tampil_namaBarangPinjam()+ "\n");
        memo_dataKembali.append("Tanggal Pengembalian : " + kembali.tampil_tglKembali() + "\n");
        memo_dataKembali.append("Jumlah yang Dikembalikan : " + kembali.tampil_jmlKembali() + "\n");
        memo_dataKembali.append("Jumlah yang Belum Dikembalikan : " + kembali.tampil_blmKembali() + "\n");
        memo_dataKembali.append("Biaya Peminjaman : " + kembali.tampil_biayaKembali()+ "\n");
    }//GEN-LAST:event_btn_cetakKembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_PengembalianBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_PengembalianBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_PengembalianBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_PengembalianBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_PengembalianBarang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cetakKembali;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea memo_dataKembali;
    private javax.swing.JTextField txt_idkembali;
    private javax.swing.JTextField txt_jmlkembali;
    private javax.swing.JTextField txt_jmlpinjam;
    private javax.swing.JTextField txt_namabarangkembali;
    private javax.swing.JTextField txt_tglkembali;
    // End of variables declaration//GEN-END:variables
}
